### ISSUE TITLE
6.0 not working in frontend anymore

### ISSUE THREAD

**Issue by ghost** [sindresorhus/neat-csv#11]
Hi,

Version 5 worked great in my frontend app (though I haven't tested the csv feature for some time). With 6.0 I got the following, hard to trace, error *just by importing* the `neat-csv` module:

```
TypeError: The "original" argument must be of type Function
    promisify util.js:602
    <anonymous> index.js:7
    js vendor.js:5746
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> index.js:6
    <anonymous> index.js:22
    js vendor.js:5722
    __webpack_require__ app.js:854
    fn app.js:151
    <anonymous> index.js:7
    node_modules index.js:23
    __webpack_require__ app.js:854
    fn app.js:151
```
Downgraded to 5.2 again and the error disappeared.
Is this package now node only?

**Comment by sindresorhus** [comment]
This package was always Node.js only. You can generally make Node.js modules work in the browser using shims, but there's no guarantee that the shims are not buggy or incomplete. You'll need at least a shim for the `util.promisify` method and `stream.pipeline`.

**Comment by ghost** [comment]
Alright, thanks for explaining. Will just use `csv-parser` then.

**Comment by rodvlopes** [comment]
I downgraded to 5.2 and is working again.
