### ISSUE TITLE
Error: Can't resolve 'node:buffer'

### ISSUE THREAD

**Issue by Genero-Jay** [sindresorhus/neat-csv#14]
I'm getting an error when trying to use this module:

```
Error: Webpack Compilation Error
./node_modules/neat-csv/index.js
Module not found: Error: Can't resolve 'node:buffer' 
```

Any suggestions?

**Comment by sindresorhus** [comment]
This is a problem with Webpack.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
