### ISSUE TITLE
Broken with node 14 or earlier

### ISSUE THREAD

**Issue by darkmavis1980** [sindresorhus/neat-csv#15]
I'm using this package for a project, and we use Node.js 14, I see that version `7.0.0` use ESM, which is cool, but it's totally broken with anything below Node v16, as I'm getting this error:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module
```
I see that the latest changes with this package dropped completely the support for anything apart from the current LTS version, which is a bit dangerous as a lot of people still use older but still supported LTS versions of Node, like 12 and 14.

**Comment by darkmavis1980** [comment]
Btw a solution to support CommonJS and ESM can be found [here](https://the-guild.dev/blog/support-nodejs-esm)

**Comment by sindresorhus** [comment]
Both Node.js 12 and Node.js 14 are fully supported, but it does require ESM: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

I have no plans to bring back CommonJS support: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#gistcomment-3850849
