### ISSUE TITLE
Lots of errors starting with "No matching export in ...."

### ISSUE THREAD

**Issue by jeffmiko** [sindresorhus/neat-csv#16]
I'm using in a VueJS app. I get a few errors so I can't use.

[ERROR] No matching export in "browser-external:node:util" for import "promisify"
    node_modules/neat-csv/index.js:1:8:
      1 │ import {promisify} from 'node:util';
        ╵         ~~~~~~~~~

 [ERROR] No matching export in "browser-external:node:stream" for import "Readable"
    node_modules/neat-csv/index.js:2:8:
      2 │ import {Readable as ReadableStream, pipeline} from 'node:stream';
        ╵         ~~~~~~~~

 ERROR] No matching export in "browser-external:node:buffer" for import "Buffer"
    node_modules/neat-csv/index.js:4:8:
      4 │ import {Buffer} from 'node:buffer';
        ╵         ~~~~~~

**Comment by sindresorhus** [comment]
This would be better asked in a Vue.js support channel.

**Comment by jeffmiko** [comment]
Every other library I am using works fine in Vue. Just this one. So I don't think its a Vue issue. No worries. I found another library to use.
