### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module' 

### ISSUE THREAD

**Issue by mikeymckay** [sindresorhus/neat-csv#18]
....SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (8:0) while parsing

This seems to be result from trying to keep the javascript pure (based on reading through other issues) versus adding something simple to make it work within browsers (via browserify for example). Virtually every other npm package works perfectly, so this is disappointing.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
