### ISSUE TITLE
Error when importing module

### ISSUE THREAD

**Issue by brad426** [sindresorhus/neat-csv#19]
When I import this library into my **browser** javascript using:
`import neatCsv from 'neat-csv'`

I get the following errors:
```
Uncaught Error: Module "stream" has been externalized for browser compatibility. Cannot access "stream.Transform" in client code.
    at Object.get (browser-external:stream:9:13)
    at ../../node_modules/csv-parser/index.js (index.js:1:9)
    at __require (chunk-HUBM7RA2.js?v=169fedf8:8:50)
    at index.js:5:23
```

**Comment by sindresorhus** [comment]
This package is meant for Node.js. You are of course free to use it in the browser, but I cannot provide support for various build tools. This case seems like a problem with your build tool.
