### ISSUE TITLE
ES6 -> ES5 in npm package

### ISSUE THREAD

**Issue by kachkaev** [sindresorhus/neat-csv#2]
I'm using create-react-app and its webpack config does not apply babel to stuff in `node_modules`. The app works in dev mode because Chrome understands ES6 pretty well already, but when I run `yarn build`, this error shows up:

```
Failed to compile.

static/js/main.582ff19c.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/neat-csv/index.js:6,0]
```

The reason is `=>` in `index.js`, which is not expected. Could you please move from ES6 to ES5 in the published version?

Thanks for the wrapper! Saves some time re-implementing it in every new project :–)

**Comment by kachkaev** [comment]
I  temporary copied `index.js` to my `src`, so it goes through babel now:

```js
// import neatCsv from 'neat-csv';
import neatCsv from './lib/neat-csv';
```

**Comment by kachkaev** [comment]
Relevant discussion:
https://github.com/facebookincubator/create-react-app/issues/1125

**Comment by sindresorhus** [comment]
In short, no. Longer answer: https://github.com/sindresorhus/ama/issues/446#issuecomment-281014491

**Comment by kachkaev** [comment]
Your package, your rules :–)

For those who also use `create-react-app` or a similar framework with a preconfigured webpack, here is what you can do:

1.  Create `src/lib/neat-csv.js`:

    ```js
    /* eslint-disable */
    'use strict';
    const intoStream = require('into-stream');
    const csvParser = require('csv-parser');
    const getStream = require('get-stream');

    module.exports = (input, opts) => {
      if (typeof input === 'string' || Buffer.isBuffer(input)) {
        input = intoStream(input);
      }

      return getStream.array(input.pipe(csvParser(opts)));
    };
    ```

1.  replace `import neatCsv from 'neat-csv';` with `import neatCsv from '../lib/neat-csv'` (the path may vary depending on your current file location).

1.  `npm rm -S neat-csv; npm i -S into-stream csv-parser get-stream`

1.  Enjoy :–)
