### ISSUE TITLE
Node version does not exist in Cypress

### ISSUE THREAD

**Issue by TrevinAvery** [sindresorhus/neat-csv#21]
I am using this package within a Cypress test. In the latest version, this line fails
https://github.com/sindresorhus/neat-csv/blob/dac3764a37d65ce20446a1fb33d5e35a2fbfbf3c/index.js#L19
with 

```
TypeError: Cannot read properties of undefined (reading 'split')
```

This is because `process.versions.node` is undefined in Cypress (even though it uses node).  I'm not certain why it is undefined, but it would be ideal to change this line to account for this situation.

**Comment by sindresorhus** [comment]
You need to open an issue on Cypress about that. This is a Node.js module and it expects Node.js APIs to be fully available.

**Comment by TrevinAvery** [comment]
I'm curious what node APIs this depends on. I've been using version 5.1.0 in Cypress for over a year, and it has worked just fine. It was only when I updated to 6.0.1 that I started seeing this problem.

Is it possible to make this work without node so it can run on frontend applications?
