### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Regnised** [sindresorhus/neat-csv#6]
Hello, I have CSV file saved on MacOS. Parsing this file [Link to CSV](https://drive.google.com/file/d/1387h_ajVOj4nSVLx4GwwRFcTpZS6GftB/view?usp=sharing)
I get space in " Vorname*". If I resave on WindowsOS Excel "Vorname*" looks good.
Thanks for your time. Ask me, if you need additional information

**Comment by sindresorhus** [comment]
From the readme:

> Convenience wrapper around the super-fast streaming csv-parser module.

You should open an issue on `csv-parser` instead.
