### ISSUE TITLE
Limit of 1024 rows

### ISSUE THREAD

**Issue by fernlop** [sindresorhus/neat-csv#7]
I only receive 1024 object keys/key-value-pairs back with neat-csv.

**Comment by sindresorhus** [comment]
I can't really help with so little info. You need to provide Node.js version, `neat-csv` version, and some code that reproduces the problem.

**Comment by fernlop** [comment]
Im sorry i thought this was a problem with the package because it ended at exactly 1024 entries. 
The problem was that one field on the 1025th entry contained a single quotation mark. After this all following rows didn't work.
